---
title: "Prep PUMS data for analysis"
format: 
  html:
    embed-resources: true
    toc: true
editor: source
execute:
  echo: true
  warning: false
  message: false
---

## Prep starting data

```{r setup}
library(tidyverse)
library(here)

source(here("R", "process-pums.R"))
source(here("R", "prep001.R"))
source(here("R", "add-opt-out-prob.R"))
source(here("R", "add-opt-out-decision.R"))
```

### DC only - for exploratory

10% sample of total population

```{r, message = FALSE}
df_dc <- process_pums("DC")
saveRDS(df_dc, file = paste(here("data", "pums"), "pums-dc.rds", sep = "/"))
```

### starting-data-001

DC and IA only
attributes: age bucket, sex, race simple

```{r, message = FALSE}
prep001 <- prep001()

lookup001 <- prep001$lookup

starting001 <- prep001$starting %>%
  add_opt_out_prob() %>%
  add_opt_out_decision(opt_out_prob, 0.5)
  
saveRDS(starting001, file = paste(here("data", "starting"), "starting-data-001.rds", sep = "/"))
saveRDS(lookup001, file = paste(here("data", "lookup"), "lookup-data-001.rds", sep = "/"))
```

